"""catalog.json artifact tests (issue #37).

The artifact is generated by scripts/generate-catalog-json.py from the
static catalog model — cross-language consumers (Go/Pulumi) read it, so
its shape and determinism are contract. Determinism matters most: two
runs on the same model must be byte-identical or git diffs go noisy.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog.json"
GENERATOR = ROOT / "scripts" / "generate-catalog-json.py"


def _run(*args: str) -> str:
    r = subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert r.returncode == 0, f"generator failed: {r.stderr}"
    return r.stdout


def test_artifact_exists_with_schema():
    doc = json.loads(CATALOG.read_text())
    assert doc["schema"] == "shc-catalog/1"
    assert doc["api_version"]
    assert doc["toolkit_version"]


def test_all_four_lines_with_storefront_triples():
    doc = json.loads(CATALOG.read_text())
    assert {
        k: (v["order_form_id"], v["module_group_id"], v["package_group_id"])
        for k, v in doc["lines"].items()
    } == {
        "nvme": (1, 4, 3),
        "hdd": (3, 8, 5),
        "ssd": (7, 7, 10),
        "dev": (11, 7, 14),
    }


def test_twenty_packages_with_pricing_and_specs():
    doc = json.loads(CATALOG.read_text())
    assert len(doc["packages"]) == 20
    by_id = {p["package_id"]: p for p in doc["packages"]}
    nvme_starter = by_id[23]
    assert nvme_starter["spec"] == "nvme-1c-4gb"
    assert nvme_starter["pricing_id_daily"] == 55
    assert nvme_starter["daily_price"] == "0.26"
    dev_starter = by_id[80]
    assert dev_starter["templates"][-3:] == [
        "firecracker-cloud",
        "openwrt-cloud",
        "pve-ve-cloud",
    ]
    for p in doc["packages"]:
        assert set(p["option_ids"]) == {"ram", "cpu", "disk", "ipv4s"}


def test_deterministic_output():
    """A second generation must be byte-identical to the committed file."""
    r = subprocess.run(
        [
            sys.executable,
            "-c",
            "import sys; sys.argv = ['x']; "
            f"sys.path.insert(0, {str(ROOT / 'scripts')!r}); "
            "import importlib.util as u; "
            "s = u.spec_from_file_location('gcj', "
            f"{str(GENERATOR)!r}); "
            "m = u.module_from_spec(s); s.loader.exec_module(m); "
            "import json as j; print(m.render(m.build()), end='')",
        ],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert r.returncode == 0, r.stderr
    assert r.stdout == CATALOG.read_text()
