#!/usr/bin/env python3
"""Fetch the live SHC catalog and regenerate catalog_cache.json + sizes.py.

Run locally or in CI. Requires SHC_API_KEY in env.

Usage:
    python scripts/generate_sizes.py           # fetch live + regenerate both artifacts
    python scripts/generate_sizes.py --check   # compare live vs cached, exit 1 if drift
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE_PATH = ROOT / "shc_toolkit" / "catalog_cache.json"
SIZES_PATH = ROOT / "shc_toolkit" / "sizes.py"

LINE_ORDER = ["nvme", "ssd", "hdd", "dev"]
TERM_ORDER = {"day": 0, "week": 1, "month": 2, "year": 3}


def fetch_catalog() -> list[dict]:
    sys.path.insert(0, str(ROOT))
    from shc_toolkit.client import SHCClient
    return SHCClient().get_catalog()


def normalize_package(raw: dict) -> dict:
    """Flatten a raw catalog package into the cached shape."""
    pkg_id = raw["package_id"]
    name = raw["name"]
    line = _detect_line(raw)

    pkg = {
        "package_id": pkg_id,
        "name": name,
        "line": line,
        "cpu": raw["cpu"],
        "memory_mb": raw["memory_mb"],
        "disk_gb": raw["disk_gb"],
        "bandwidth_gb": raw["bandwidth_gb"],
        "ipv4": raw["ipv4"],
        "ipv6": raw["ipv6"],
        "snapshot_limit": raw.get("snapshot_limit"),
        "backup_limit": raw.get("backup_limit"),
        "template": raw.get("template"),
        "module_groups": raw.get("module_groups", []),
        "default_module_group_id": raw.get("default_module_group_id"),
        "module_group_required": raw.get("module_group_required", False),
        "order_form_id": raw.get("order_form_id"),
        "order_form_label": raw.get("order_form_label"),
        "pricings": _extract_pricings(raw),
        "config_options": _extract_config_options(raw),
    }
    return pkg


def _detect_line(raw: dict) -> str:
    label = (raw.get("order_form_label") or "").lower()
    name = raw.get("name", "").lower()
    if "dev" in label or "dev" in name:
        return "dev"
    if "hdd" in label or "hdd" in name:
        return "hdd"
    if "ssd" in label or "ssd" in name:
        return "ssd"
    return "nvme"


def _extract_pricings(raw: dict) -> list[dict]:
    out = []
    for p in raw.get("pricing", []):
        out.append({
            "pricing_id": p["pricing_id"],
            "term": p.get("term"),
            "period": p.get("period"),
            "price": p.get("price"),
            "renew": p.get("renew"),
            "setup_fee": p.get("setup_fee"),
            "currency": p.get("currency", "USD"),
        })
    out.sort(key=lambda x: TERM_ORDER.get(x["period"], 99))
    return out


def _extract_config_options(raw: dict) -> dict[str, dict]:
    """Extract config options keyed by option name, deduped across billing terms.

    The catalog returns one available_config_options block per billing term, each
    containing the same options with the same option_ids and values. We keep one
    canonical copy (from the first block) since option_ids and value sets are
    identical across terms — only pricing differs.
    """
    seen = {}
    for block in raw.get("available_config_options", []):
        for opt in block.get("options", []):
            name = opt["name"]
            if name in seen:
                continue
            seen[name] = {
                "option_id": opt["option_id"],
                "label": opt.get("label", name),
                "addable": opt.get("addable", False),
                "editable": opt.get("editable", False),
                "values": [
                    {
                        "value": v["value"],
                        "name": v["name"],
                        "default": v.get("default", False),
                    }
                    for v in opt.get("values", [])
                ],
            }
    return seen


def build_cache(catalog: list[dict]) -> dict:
    packages = [normalize_package(p) for p in catalog]
    packages.sort(key=lambda p: (LINE_ORDER.index(p["line"]) if p["line"] in LINE_ORDER else 99, p["cpu"], p["package_id"]))
    return {
        "_meta": {
            "description": "Local cache of SHC catalog data. Auto-generated by scripts/generate_sizes.py from GET /ordering/catalog. Do not edit by hand.",
            "source": "https://blesta.sovereignhybridcompute.com/user-api/v2/ordering/catalog",
            "package_count": len(packages),
        },
        "packages": packages,
    }


def render_sizes_py(cache: dict) -> str:
    """Render the sizes.py module from a cache dict."""
    pkgs = cache["packages"]
    entries = []
    legacy = []
    for p in pkgs:
        line = p["line"]
        cpu = p["cpu"]
        ram_gb = p["memory_mb"] // 1024
        spec_key = f"{line}-{cpu}c-{ram_gb}gb"
        daily = next((pr for pr in p["pricings"] if pr["period"] == "day"), None)
        daily_price = daily["price"] if daily else "0.00"
        entries.append(
            f'    {spec_key!r}: {{"package_id": {p["package_id"]}, "cpu": {cpu}, "ram_mb": {p["memory_mb"]}, '
            f'"disk_gb": {p["disk_gb"]}, "line": {line!r}, "name": {p["name"]!r}, '
            f'"daily_price": {daily_price!r}}},'
        )
    return _SIZES_TEMPLATE.format(entries="\n".join(entries))


_SIZES_TEMPLATE = '''"""VM size catalog for SHC, auto-generated from GET /ordering/catalog.

Spec-encoding names follow the {line}-{cpu}c-{ram}gb convention:
    nvme-2c-8gb, ssd-1c-4gb, hdd-4c-16gb, dev-2c-8gb

The static SIZE_MAP is the default fast path (no network, no auth).
For live pricing, use SHCClient.get_catalog().

Regenerate:
    python scripts/generate_sizes.py
"""

from __future__ import annotations

SIZE_MAP: dict[str, dict] = {
{entries}
}


def resolve_size(size: str) -> tuple[int, int]:
    """Resolve a spec-encoding size name to (package_id, pricing_id).

    Args:
        size: Size name like ``nvme-2c-8gb``, ``hdd-1c-4gb``, ``dev-4c-16gb``.

    Returns:
        (package_id, pricing_id) tuple.

    Raises:
        ValueError: If size name is not recognized.
    """
    entry = SIZE_MAP.get(size.lower().strip())
    if not entry:
        valid = ", ".join(SIZE_MAP.keys())
        raise ValueError(f"Unknown size '{{size}}'. Valid sizes: {{valid}}")
    return entry["package_id"], _daily_pricing_id(entry)


def resolve_specs(
    cpu: int | None = None,
    ram_mb: int | None = None,
    disk_gb: int | None = None,
    *,
    line: str | None = None,
) -> tuple[int, int]:
    """Find the cheapest plan that meets or exceeds the requested specs.

    Args:
        cpu: Minimum CPU cores required.
        ram_mb: Minimum RAM in MB required.
        disk_gb: Minimum disk in GB required.
        line: Filter by ``nvme``, ``ssd``, ``hdd``, or ``dev``.

    Returns:
        (package_id, pricing_id) of the cheapest matching plan.

    Raises:
        ValueError: If no plan matches the specs.
    """
    candidates = []
    for entry in SIZE_MAP.values():
        if line and entry["line"] != line:
            continue
        if cpu and entry["cpu"] < cpu:
            continue
        if ram_mb and entry["ram_mb"] < ram_mb:
            continue
        if disk_gb and entry["disk_gb"] < disk_gb:
            continue
        candidates.append(entry)
    if not candidates:
        raise ValueError(
            f"No plan matches specs: cpu>={{cpu}}, ram_mb>={{ram_mb}}, disk_gb>={{disk_gb}}, line={{line}}"
        )
    cheapest = min(candidates, key=lambda e: float(e["daily_price"]))
    return cheapest["package_id"], _daily_pricing_id(cheapest)


def list_sizes(line: str | None = None) -> list[dict]:
    """List all available sizes with their specs.

    Args:
        line: Filter by ``nvme``, ``ssd``, ``hdd``, or ``dev``. None = all.

    Returns:
        List of size dicts with size, package_id, cpu, ram_mb, disk_gb, line, name, daily_price.
    """
    result = []
    for name, entry in SIZE_MAP.items():
        if line and entry["line"] != line:
            continue
        result.append({{"size": name, **entry}})
    return result


def spec_name(line: str, cpu: int, ram_mb: int) -> str:
    """Generate a spec-encoding size name from specs."""
    return f"{{line}}-{{cpu}}c-{{ram_mb // 1024}}gb"


def _daily_pricing_id(entry: dict) -> int:
    """Daily pricing_id for an entry. Falls back to reading from catalog_cache.json."""
    return _PRICING_LOOKUP.get(entry["package_id"], 0)


_PRICING_LOOKUP: dict[int, int] = {
{pricing_lookup}
}
'''


_SIZES_TEMPLATE_V2 = '''"""VM size catalog for SHC, auto-generated from GET /ordering/catalog.

Spec-encoding names follow the {line}-{cpu}c-{ram}gb convention:
    nvme-2c-8gb, ssd-1c-4gb, hdd-4c-16gb, dev-2c-8gb

The static SIZE_MAP is the default fast path (no network, no auth).
For live pricing, use SHCClient.get_catalog().

Regenerate:
    python scripts/generate_sizes.py
"""

from __future__ import annotations

SIZE_MAP: dict[str, dict] = {
__ENTRIES__
}


def resolve_size(size: str) -> tuple[int, int]:
    """Resolve a spec-encoding size name to (package_id, pricing_id).

    Args:
        size: Size name like `nvme-2c-8gb`, `hdd-1c-4gb`, `dev-4c-16gb`.

    Returns:
        (package_id, pricing_id) tuple.

    Raises:
        ValueError: If size name is not recognized.
    """
    entry = SIZE_MAP.get(size.lower().strip())
    if not entry:
        valid = ", ".join(SIZE_MAP.keys())
        raise ValueError(f"Unknown size \\"{size}\\". Valid sizes: {valid}")
    return entry["package_id"], _PRICING_LOOKUP[entry["package_id"]]


def resolve_specs(
    cpu: int | None = None,
    ram_mb: int | None = None,
    disk_gb: int | None = None,
    *,
    line: str | None = None,
) -> tuple[int, int]:
    """Find the cheapest plan that meets or exceeds the requested specs.

    Args:
        cpu: Minimum CPU cores required.
        ram_mb: Minimum RAM in MB required.
        disk_gb: Minimum disk in GB required.
        line: Filter by `nvme`, `ssd`, `hdd`, or `dev`. None = all.

    Returns:
        (package_id, pricing_id) of the cheapest matching plan.

    Raises:
        ValueError: If no plan matches the specs.
    """
    candidates = []
    for entry in SIZE_MAP.values():
        if line and entry["line"] != line:
            continue
        if cpu and entry["cpu"] < cpu:
            continue
        if ram_mb and entry["ram_mb"] < ram_mb:
            continue
        if disk_gb and entry["disk_gb"] < disk_gb:
            continue
        candidates.append(entry)
    if not candidates:
        raise ValueError(
            f"No plan matches specs: cpu>={cpu}, ram_mb>={ram_mb}, disk_gb>={disk_gb}, line={line}"
        )
    cheapest = min(candidates, key=lambda e: float(e["daily_price"]))
    return cheapest["package_id"], _PRICING_LOOKUP[cheapest["package_id"]]


def list_sizes(line: str | None = None) -> list[dict]:
    """List all available sizes with their specs.

    Args:
        line: Filter by `nvme`, `ssd`, `hdd`, or `dev`. None = all.

    Returns:
        List of size dicts with size, package_id, cpu, ram_mb, disk_gb, line, name, daily_price.
    """
    result = []
    for name, entry in SIZE_MAP.items():
        if line and entry["line"] != line:
            continue
        result.append({"size": name, **entry})
    return result


def spec_name(line: str, cpu: int, ram_mb: int) -> str:
    """Generate a spec-encoding size name from specs."""
    return f"{line}-{cpu}c-{ram_mb // 1024}gb"


_PRICING_LOOKUP: dict[int, int] = {
__PRICING_LOOKUP__
}
'''


def render_sizes_py_v2(cache: dict) -> str:
    """Render sizes.py with a pricing lookup table for all packages."""
    pkgs = cache["packages"]
    entries_lines = []
    pricing_lines = []
    for p in pkgs:
        line = p["line"]
        cpu = p["cpu"]
        ram_gb = p["memory_mb"] // 1024
        spec_key = f"{line}-{cpu}c-{ram_gb}gb"
        daily = next((pr for pr in p["pricings"] if pr["period"] == "day"), None)
        daily_price = daily["price"] if daily else "0.00"
        daily_pid = daily["pricing_id"] if daily else 0
        entries_lines.append(
            f'    "{spec_key}": {{"package_id": {p["package_id"]}, "cpu": {cpu}, "ram_mb": {p["memory_mb"]}, '
            f'"disk_gb": {p["disk_gb"]}, "line": "{line}", "name": "{p["name"]}", '
            f'"daily_price": "{daily_price}"}},'
        )
        pricing_lines.append(f'    {p["package_id"]}: {daily_pid},  # {spec_key}')

    entries_str = "\n".join(entries_lines)
    pricing_str = "\n".join(pricing_lines)
    return _SIZES_TEMPLATE_V2.replace("__ENTRIES__", entries_str).replace("__PRICING_LOOKUP__", pricing_str)


def check_drift(live: list[dict], cached: dict) -> list[str]:
    """Return list of human-readable drift descriptions. Empty = no drift."""
    diffs = []
    live_pkgs = {p["package_id"]: p for p in live}
    cached_pkgs = {p["package_id"]: p for p in cached.get("packages", [])}

    for pkg_id in sorted(set(live_pkgs) | set(cached_pkgs)):
        if pkg_id not in cached_pkgs:
            diffs.append(f"package {pkg_id} added live: {live_pkgs[pkg_id]['name']}")
            continue
        if pkg_id not in live_pkgs:
            diffs.append(f"package {pkg_id} removed live (still cached): {cached_pkgs[pkg_id]['name']}")
            continue
        lp, cp = live_pkgs[pkg_id], cached_pkgs[pkg_id]
        for field in ("cpu", "memory_mb", "disk_gb", "bandwidth_gb", "name"):
            lv = lp.get(field)
            cv = cp.get(field)
            if lv != cv:
                diffs.append(f"package {pkg_id} field '{field}': cached={cv!r} live={lv!r}")
        live_daily = next((pr["price"] for pr in lp.get("pricing", []) if pr.get("period") == "day"), None)
        cached_daily = next((pr["price"] for pr in cp.get("pricings", []) if pr.get("period") == "day"), None)
        if live_daily is not None and cached_daily is not None and live_daily != cached_daily:
            diffs.append(f"package {pkg_id} daily price: cached={cached_daily!r} live={live_daily!r}")
    return diffs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift, do not write files")
    args = parser.parse_args()

    print("Fetching live catalog...", file=sys.stderr)
    live = fetch_catalog()
    new_cache = build_cache(live)

    if args.check:
        existing = json.loads(CACHE_PATH.read_text()) if CACHE_PATH.exists() else {"packages": []}
        diffs = check_drift(live, existing)
        if not diffs:
            print("No drift detected.", file=sys.stderr)
            return 0
        print("DRIFT DETECTED:", file=sys.stderr)
        for d in diffs:
            print(f"  - {d}", file=sys.stderr)
        return 1

    CACHE_PATH.write_text(json.dumps(new_cache, indent=2) + "\n")
    print(f"Wrote {len(new_cache['packages'])} packages -> {CACHE_PATH.relative_to(ROOT)}", file=sys.stderr)

    SIZES_PATH.write_text(render_sizes_py_v2(new_cache))
    print(f"Wrote sizes.py -> {SIZES_PATH.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
