#!/usr/bin/env bash
# Regenerate the auto-generated Python client from the SHC OpenAPI spec.
#
# Usage:
#   pip install openapi-python-client
#   bash scripts/generate_client.sh
#
# This script:
# 1. Reads shc_toolkit/openapi.json (the cached spec)
# 2. Fixes 2 known schema quirks (unwrap_hints empty arrays)
# 3. Generates the Python client via openapi-python-client
# 4. Moves the output into shc_toolkit/generated/
# 5. Restores the package __init__.py with import guard
#
# The generated client provides 100% API endpoint coverage + full
# Pydantic type safety. SHCClient (hand-written) wraps it and adds
# retry, cost tracking, confirmation flow, cache, and MCP transport.
#
# Do NOT edit files in shc_toolkit/generated/ by hand — they will be
# overwritten by this script.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="$REPO_ROOT/shc_toolkit/openapi.json"
OUTPUT_DIR="$REPO_ROOT/shc_toolkit/generated"
TMP_DIR="$(mktemp -d)"

trap 'rm -rf "$TMP_DIR"' EXIT

echo "→ Fixing schema quirks in spec..."
python3 - "$SPEC" "$TMP_DIR/openapi-fixed.json" << 'PYEOF'
import json, sys
spec = json.load(open(sys.argv[1]))
fixed = 0
for path, methods in spec.get('paths', {}).items():
    for method, op in methods.items():
        if not isinstance(op, dict): continue
        for code, resp in op.get('responses', {}).items():
            if not isinstance(resp, dict): continue
            schema = resp.get('content', {}).get('application/json', {}).get('schema', {})
            if not isinstance(schema, dict): continue
            props = schema.get('properties', {}).get('data', {}).get('properties', {})
            if 'unwrap_hints' in props:
                items = props['unwrap_hints'].get('items', None)
                if items == [] or items == {}:
                    props['unwrap_hints']['items'] = {"type": "object", "additionalProperties": True}
                    fixed += 1
with open(sys.argv[2], 'w') as f:
    json.dump(spec, f, indent=2)
print(f"  Fixed {fixed} schema quirks")
PYEOF

echo "→ Generating Python client..."
openapi-python-client generate \
  --path "$TMP_DIR/openapi-fixed.json" \
  --meta none \
  --output-path "$TMP_DIR/client" 2>&1 | grep -v "^$" || true

echo "→ Installing into shc_toolkit/generated/..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -r "$TMP_DIR/client/"* "$OUTPUT_DIR/"

# Restore the package __init__.py with import guard
cat > "$OUTPUT_DIR/__init__.py" << 'INITEOF'
"""Auto-generated SHC API client from OpenAPI spec.

Regenerated by `scripts/generate_client.sh`. Do not edit files in
this directory by hand — they will be overwritten.

Usage:
    pip install shc-toolkit[generated]
    from shc_toolkit.generated import Client
"""
try:
    from .client import Client
except ImportError as e:
    raise ImportError(
        "The generated client requires httpx and attrs. "
        "Install with: pip install shc-toolkit[generated]"
    ) from e
INITEOF

# Add py.typed marker for type checkers
touch "$OUTPUT_DIR/py.typed"

COUNT=$(find "$OUTPUT_DIR" -name "*.py" | wc -l)
echo "→ Done. $COUNT Python files in $OUTPUT_DIR"
echo "→ Install dependencies: pip install httpx attrs python-dateutil"
