#!/usr/bin/env bash
# Regenerate the auto-generated Python client from the SHC OpenAPI spec.
#
# Usage:
#   pip install openapi-python-client
#   bash scripts/generate_client.sh
#
# This script:
# 1. Reads shc_toolkit/openapi.json (the cached spec)
# 2. Fixes 2 known schema quirks (unwrap_hints empty arrays)
# 3. Generates the Python client via openapi-python-client
# 4. Moves the output into shc_toolkit/generated/
# 5. Restores the package __init__.py with import guard
#
# The generated client provides 100% API endpoint coverage + full
# Pydantic type safety. SHCClient (hand-written) wraps it and adds
# retry, cost tracking, confirmation flow, cache, and MCP transport.
#
# Do NOT edit files in shc_toolkit/generated/ by hand — they will be
# overwritten by this script.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="$REPO_ROOT/shc_toolkit/openapi.json"
OUTPUT_DIR="$REPO_ROOT/shc_toolkit/generated"
TMP_DIR="$(mktemp -d)"

trap 'rm -rf "$TMP_DIR"' EXIT

echo "→ Fixing schema quirks in spec..."
python3 - "$SPEC" "$TMP_DIR/openapi-fixed.json" << 'PYEOF'
import json, sys
spec = json.load(open(sys.argv[1]))
fixed = 0
for path, methods in spec.get('paths', {}).items():
    for method, op in methods.items():
        if not isinstance(op, dict): continue
        for code, resp in op.get('responses', {}).items():
            if not isinstance(resp, dict): continue
            schema = resp.get('content', {}).get('application/json', {}).get('schema', {})
            if not isinstance(schema, dict): continue
            props = schema.get('properties', {}).get('data', {}).get('properties', {})
            if 'unwrap_hints' in props:
                items = props['unwrap_hints'].get('items', None)
                if items == [] or items == {}:
                    props['unwrap_hints']['items'] = {"type": "object", "additionalProperties": True}
                    fixed += 1

# Deep-fix ALL empty array schemas anywhere in the spec
def fix_empty_arrays_deep(obj):
    global fixed
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k == "items" and v == []:
                obj[k] = {"type": "object", "additionalProperties": True}
                fixed += 1
            elif isinstance(v, (dict, list)):
                fix_empty_arrays_deep(v)
    elif isinstance(obj, list):
        for item in obj:
            if isinstance(item, (dict, list)):
                fix_empty_arrays_deep(item)
fix_empty_arrays_deep(spec)
with open(sys.argv[2], 'w') as f:
    json.dump(spec, f, indent=2)
print(f"  Fixed {fixed} schema quirks")

# Fix duplicate enum keys (SHC spec bug: cloud-init-policy-violation vs cloud_init_policy_violation)
# openapi-python-client normalizes both to CLOUD_INIT_POLICY_VIOLATION → collision
spec2 = json.load(open(sys.argv[2]))
enum_fixed = 0
def fix_enums(obj, path=""):
    global enum_fixed
    if isinstance(obj, dict):
        if "enum" in obj and isinstance(obj["enum"], list):
            seen_keys = set()
            deduped = []
            for val in obj["enum"]:
                key = val.upper().replace("-", "_") if isinstance(val, str) else str(val)
                if key not in seen_keys:
                    seen_keys.add(key)
                    deduped.append(val)
                else:
                    enum_fixed += 1
            obj["enum"] = deduped
        for k, v in obj.items():
            if isinstance(v, (dict, list)):
                fix_enums(v, f"{path}.{k}")
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            if isinstance(item, (dict, list)):
                fix_enums(item, f"{path}[{i}]")
fix_enums(spec2)
with open(sys.argv[2], 'w') as f:
    json.dump(spec2, f, indent=2)
if enum_fixed:
    print(f"  Fixed {enum_fixed} duplicate enum value(s)")
PYEOF

echo "→ Generating Python client..."
openapi-python-client generate \
  --path "$TMP_DIR/openapi-fixed.json" \
  --meta none \
  --output-path "$TMP_DIR/client" 2>&1 | grep -v "^$" || true

echo "→ Installing into shc_toolkit/generated/..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -r "$TMP_DIR/client/"* "$OUTPUT_DIR/"

# Restore the package __init__.py with import guard
cat > "$OUTPUT_DIR/__init__.py" << 'INITEOF'
"""Auto-generated SHC API client from OpenAPI spec.

Regenerated by `scripts/generate_client.sh`. Do not edit files in
this directory by hand — they will be overwritten.

Usage:
    pip install shc-toolkit[generated]
    from shc_toolkit.generated import Client
"""
try:
    from .client import Client
except ImportError as e:
    raise ImportError(
        "The generated client requires httpx and attrs. "
        "Install with: pip install shc-toolkit[generated]"
    ) from e
INITEOF

# Add py.typed marker for type checkers
touch "$OUTPUT_DIR/py.typed"

COUNT=$(find "$OUTPUT_DIR" -name "*.py" | wc -l)
echo "→ Done. $COUNT Python files in $OUTPUT_DIR"
echo "→ Install dependencies: pip install httpx attrs python-dateutil"
