---
name: security

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  bandit:
    name: bandit security linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - run: pip install bandit -q
      - run: bandit -r shc_toolkit/ -ll

  safety:
    name: safety dependency scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - run: pip install safety -q
      - run: pip install --upgrade "setuptools>=83.0.0" -q
      - run: safety check --short-report

  pip-audit:
    name: pip-audit dependency scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - run: pip install pip-audit -q
      - run: pip install --upgrade "setuptools>=83.0.0" -q
      - run: pip-audit
